class ContentBank {
  static const Map<String, List<Map<String, String>>> words = {
    'A1': [
      {"en": "Apple", "tr": "Elma"},
      {"en": "Water", "tr": "Su"},
      {"en": "Cat", "tr": "Kedi"},
      {"en": "Dog", "tr": "Köpek"},
      {"en": "Book", "tr": "Kitap"},
      {"en": "Pen", "tr": "Kalem"},
      {"en": "School", "tr": "Okul"},
      {"en": "Teacher", "tr": "Öğretmen"},
      {"en": "Student", "tr": "Öğrenci"},
      {"en": "Car", "tr": "Araba"},
      {"en": "Bus", "tr": "Otobüs"},
      {"en": "House", "tr": "Ev"},
      {"en": "Room", "tr": "Oda"},
      {"en": "Door", "tr": "Kapı"},
      {"en": "Window", "tr": "Pencere"},
      {"en": "Table", "tr": "Masa"},
      {"en": "Chair", "tr": "Sandalye"},
      {"en": "Phone", "tr": "Telefon"},
      {"en": "Computer", "tr": "Bilgisayar"},
      {"en": "Friend", "tr": "Arkadaş"},
      {"en": "Family", "tr": "Aile"},
      {"en": "Mother", "tr": "Anne"},
      {"en": "Father", "tr": "Baba"},
      {"en": "Sister", "tr": "Kız Kardeş"},
      {"en": "Brother", "tr": "Erkek Kardeş"},
      {"en": "Love", "tr": "Aşk"},
      {"en": "Time", "tr": "Zaman"},
      {"en": "Day", "tr": "Gün"},
      {"en": "Night", "tr": "Gece"},
      {"en": "Morning", "tr": "Sabah"},
      {"en": "Sun", "tr": "Güneş"},
      {"en": "Moon", "tr": "Ay"},
      {"en": "Star", "tr": "Yıldız"},
      {"en": "Rain", "tr": "Yağmur"},
      {"en": "Snow", "tr": "Kar"},
      {"en": "Tree", "tr": "Ağaç"},
      {"en": "Flower", "tr": "Çiçek"},
      {"en": "Bird", "tr": "Kuş"},
      {"en": "Fish", "tr": "Balık"},
      {"en": "Bread", "tr": "Ekmek"},
      {"en": "Milk", "tr": "Süt"},
      {"en": "Coffee", "tr": "Kahve"},
      {"en": "Tea", "tr": "Çay"},
      {"en": "Sugar", "tr": "Şeker"},
      {"en": "Salt", "tr": "Tuz"},
      {"en": "Food", "tr": "Yemek"},
      {"en": "Hand", "tr": "El"},
      {"en": "Foot", "tr": "Ayak"},
      {"en": "Eye", "tr": "Göz"},
      {"en": "Nose", "tr": "Burun"},
      {"en": "Mouth", "tr": "Ağız"},
      {"en": "Ear", "tr": "Kulak"},
    ],
    'A2': [
      {"en": "Airport", "tr": "Havalimanı"},
      {"en": "Ticket", "tr": "Bilet"},
      {"en": "Passport", "tr": "Pasaport"},
      {"en": "Hotel", "tr": "Otel"},
      {"en": "Map", "tr": "Harita"},
      {"en": "Driver", "tr": "Sürücü"},
      {"en": "Road", "tr": "Yol"},
      {"en": "Bridge", "tr": "Köprü"},
      {"en": "Market", "tr": "Market"},
      {"en": "Money", "tr": "Para"},
      {"en": "Price", "tr": "Fiyat"},
      {"en": "Cheap", "tr": "Ucuz"},
      {"en": "Expensive", "tr": "Pahalı"},
      {"en": "Clothes", "tr": "Kıyafet"},
      {"en": "Shirt", "tr": "Gömlek"},
      {"en": "Shoes", "tr": "Ayakkabı"},
      {"en": "Doctor", "tr": "Doktor"},
      {"en": "Hospital", "tr": "Hastane"},
      {"en": "Medicine", "tr": "İlaç"},
      {"en": "Sick", "tr": "Hasta"},
      {"en": "Weather", "tr": "Hava Durumu"},
      {"en": "Hot", "tr": "Sıcak"},
      {"en": "Cold", "tr": "Soğuk"},
      {"en": "Wind", "tr": "Rüzgar"},
      {"en": "Summer", "tr": "Yaz"},
      {"en": "Winter", "tr": "Kış"},
      {"en": "Holiday", "tr": "Tatil"},
      {"en": "Job", "tr": "İş"},
      {"en": "Office", "tr": "Ofis"},
      {"en": "Meeting", "tr": "Toplantı"},
      {"en": "Manager", "tr": "Müdür"},
      {"en": "Worker", "tr": "Çalışan"},
      {"en": "Email", "tr": "E-posta"},
      {"en": "Address", "tr": "Adres"},
      {"en": "City", "tr": "Şehir"},
      {"en": "Country", "tr": "Ülke"},
      {"en": "Language", "tr": "Dil"},
      {"en": "Question", "tr": "Soru"},
      {"en": "Answer", "tr": "Cevap"},
      {"en": "Problem", "tr": "Sorun"},
      {"en": "Solution", "tr": "Çözüm"},
      {"en": "Idea", "tr": "Fikir"},
      {"en": "Dream", "tr": "Rüya"},
      {"en": "Story", "tr": "Hikaye"},
      {"en": "Movie", "tr": "Film"},
      {"en": "Song", "tr": "Şarkı"},
      {"en": "Game", "tr": "Oyun"},
      {"en": "Team", "tr": "Takım"},
    ],
    'B1': [
      {"en": "Environment", "tr": "Çevre"},
      {"en": "Pollution", "tr": "Kirlilik"},
      {"en": "Global", "tr": "Küresel"},
      {"en": "Local", "tr": "Yerel"},
      {"en": "Culture", "tr": "Kültür"},
      {"en": "Tradition", "tr": "Gelenek"},
      {"en": "Society", "tr": "Toplum"},
      {"en": "Community", "tr": "Topluluk"},
      {"en": "Education", "tr": "Eğitim"},
      {"en": "Knowledge", "tr": "Bilgi"},
      {"en": "Skill", "tr": "Beceri"},
      {"en": "Ability", "tr": "Yetenek"},
      {"en": "Experience", "tr": "Deneyim"},
      {"en": "Opportunity", "tr": "Fırsat"},
      {"en": "Challenge", "tr": "Zorluk"},
      {"en": "Success", "tr": "Başarı"},
      {"en": "Failure", "tr": "Başarısızlık"},
      {"en": "Goal", "tr": "Hedef"},
      {"en": "Purpose", "tr": "Amaç"},
      {"en": "Reason", "tr": "Sebep"},
      {"en": "Result", "tr": "Sonuç"},
      {"en": "Opinion", "tr": "Fikir"},
      {"en": "Agreement", "tr": "Anlaşma"},
      {"en": "Argument", "tr": "Tartışma"},
      {"en": "Decision", "tr": "Karar"},
      {"en": "Choice", "tr": "Seçim"},
      {"en": "Advice", "tr": "Tavsiye"},
      {"en": "Suggestion", "tr": "Öneri"},
      {"en": "Warning", "tr": "Uyarı"},
      {"en": "Promise", "tr": "Söz"},
      {"en": "Memory", "tr": "Hafıza"},
      {"en": "Imagination", "tr": "Hayal Gücü"},
      {"en": "Creativity", "tr": "Yaratıcılık"},
      {"en": "Science", "tr": "Bilim"},
      {"en": "Technology", "tr": "Teknoloji"},
      {"en": "Internet", "tr": "İnternet"},
      {"en": "Network", "tr": "Ağ"},
      {"en": "Data", "tr": "Veri"},
      {"en": "Security", "tr": "Güvenlik"},
      {"en": "Law", "tr": "Kanun"},
      {"en": "Justice", "tr": "Adalet"},
      {"en": "Crime", "tr": "Suç"},
      {"en": "Punishment", "tr": "Ceza"},
      {"en": "Freedom", "tr": "Özgürlük"},
      {"en": "Rights", "tr": "Haklar"},
      {"en": "Peace", "tr": "Barış"},
      {"en": "War", "tr": "Savaş"},
      {"en": "History", "tr": "Tarih"},
    ],
    'B2': [
      {"en": "Significant", "tr": "Önemli"},
      {"en": "Approach", "tr": "Yaklaşım"},
      {"en": "Method", "tr": "Yöntem"},
      {"en": "Strategy", "tr": "Strateji"},
      {"en": "Analysis", "tr": "Analiz"},
      {"en": "Research", "tr": "Araştırma"},
      {"en": "Evidence", "tr": "Kanıt"},
      {"en": "Conclusion", "tr": "Sonuç"},
      {"en": "Theory", "tr": "Teori"},
      {"en": "Hypothesis", "tr": "Hipotez"},
      {"en": "Concept", "tr": "Kavram"},
      {"en": "Definition", "tr": "Tanım"},
      {"en": "Context", "tr": "Bağlam"},
      {"en": "Perspective", "tr": "Bakış Açısı"},
      {"en": "Insight", "tr": "İçgörü"},
      {"en": "Innovation", "tr": "İnovasyon"},
      {"en": "Development", "tr": "Gelişim"},
      {"en": "Progress", "tr": "İlerleme"},
      {"en": "Economy", "tr": "Ekonomi"},
      {"en": "Investment", "tr": "Yatırım"},
      {"en": "Market", "tr": "Pazar"},
      {"en": "Industry", "tr": "Endüstri"},
      {"en": "Production", "tr": "Üretim"},
      {"en": "Consumption", "tr": "Tüketim"},
      {"en": "Distribution", "tr": "Dağıtım"},
      {"en": "Resource", "tr": "Kaynak"},
      {"en": "Management", "tr": "Yönetim"},
      {"en": "Leadership", "tr": "Liderlik"},
      {"en": "Organization", "tr": "Organizasyon"},
      {"en": "Institution", "tr": "Kurum"},
      {"en": "Policy", "tr": "Politika"},
      {"en": "Regulation", "tr": "Düzenleme"},
      {"en": "Authority", "tr": "Otorite"},
      {"en": "Influence", "tr": "Etki"},
      {"en": "Impact", "tr": "Darbe/Etki"},
      {"en": "Consequence", "tr": "Sonuç"},
      {"en": "Alternative", "tr": "Alternatif"},
      {"en": "Option", "tr": "Seçenek"},
      {"en": "Preference", "tr": "Tercih"},
      {"en": "Priority", "tr": "Öncelik"},
      {"en": "Requirement", "tr": "Gereksinim"},
      {"en": "Necessity", "tr": "Zorunluluk"},
      {"en": "Responsibility", "tr": "Sorumluluk"},
      {"en": "Obligation", "tr": "Yükümlülük"},
      {"en": "Capacity", "tr": "Kapasite"},
      {"en": "Potential", "tr": "Potansiyel"},
      {"en": "Performance", "tr": "Performans"},
      {"en": "Efficiency", "tr": "Verimlilik"},
    ],
  };

  static const Map<String, List<Map<String, String>>> sentences = {
    'A1': [
      {"en": "Hello, how are you?", "tr": "Merhaba, nasılsın?"},
      {"en": "I am fine, thank you.", "tr": "İyiyim, teşekkür ederim."},
      {"en": "What is your name?", "tr": "Adın ne?"},
      {"en": "My name is John.", "tr": "Benim adım John."},
      {"en": "Where are you from?", "tr": "Nerelisin?"},
      {"en": "I am from Turkey.", "tr": "Ben Türkiyeliyim."},
      {"en": "Nice to meet you.", "tr": "Tanıştığımıza memnun oldum."},
      {"en": "Good morning.", "tr": "Günaydın."},
      {"en": "Good night.", "tr": "İyi geceler."},
      {"en": "See you later.", "tr": "Sonra görüşürüz."},
      {"en": "I like ice cream.", "tr": "Dondurma severim."},
      {"en": "This is a cat.", "tr": "Bu bir kedi."},
      {"en": "The car is red.", "tr": "Araba kırmızı."},
      {"en": "I have a book.", "tr": "Bir kitabım var."},
      {"en": "She is my sister.", "tr": "O benim kız kardeşim."},
      {"en": "He is my brother.", "tr": "O benim erkek kardeşim."},
      {"en": "Can you help me?", "tr": "Bana yardım edebilir misin?"},
      {"en": "Excuse me.", "tr": "Affedersiniz."},
      {"en": "I am sorry.", "tr": "Üzgünüm."},
      {"en": "Thank you very much.", "tr": "Çok teşekkür ederim."},
    ],
    'A2': [
      {"en": "I went to the cinema yesterday.", "tr": "Dün sinemaya gittim."},
      {"en": "Did you enjoy the movie?", "tr": "Filmden zevk aldın mı?"},
      {
        "en": "We are going on holiday next week.",
        "tr": "Gelecek hafta tatile gidiyoruz.",
      },
      {"en": "I need to buy some milk.", "tr": "Biraz süt almam lazım."},
      {"en": "Can you open the window?", "tr": "Pencereyi açabilir misin?"},
      {"en": "It is raining outside.", "tr": "Dışarıda yağmur yağıyor."},
      {"en": "I do not understand.", "tr": "Anlamıyorum."},
      {"en": "Could you repeat that?", "tr": "Tekrar edebilir misin?"},
      {"en": "How much does this cost?", "tr": "Bunun fiyatı ne kadar?"},
      {
        "en": "Where is the nearest hospital?",
        "tr": "En yakın hastane nerede?",
      },
      {"en": "I have an appointment at two.", "tr": "Saat ikide randevum var."},
      {"en": "She cooks very well.", "tr": "O çok güzel yemek yapar."},
      {"en": "My phone is out of battery.", "tr": "Telefonumun şarjı bitti."},
      {"en": "Let's meet at the cafe.", "tr": "Kafede buluşalım."},
      {"en": "Do you have any brothers?", "tr": "Hiç erkek kardeşin var mı?"},
      {"en": "I usually wake up early.", "tr": "Genellikle erken uyanırım."},
      {"en": "He is playing football now.", "tr": "O şu an futbol oynuyor."},
      {"en": "We watched a great match.", "tr": "Harika bir maç izledik."},
      {"en": "I forgot my keys.", "tr": "Anahtarlarımı unuttum."},
      {"en": "Please turn off the lights.", "tr": "Lütfen ışıkları kapat."},
    ],
    'B1': [
      {
        "en": "I have been living here for five years.",
        "tr": "Beş yıldır burada yaşıyorum.",
      },
      {
        "en": "If I had money, I would buy a car.",
        "tr": "Param olsaydı araba alırdım.",
      },
      {
        "en": "You should have told me earlier.",
        "tr": "Bana daha önce söylemeliydin.",
      },
      {
        "en": "Although it was cold, we went swimming.",
        "tr": "Hava soğuk olmasına rağmen yüzmeye gittik.",
      },
      {
        "en": "I am interested in learning new languages.",
        "tr": "Yeni diller öğrenmeye ilgim var.",
      },
      {
        "en": "The manager is responsible for the project.",
        "tr": "Müdür projeden sorumlu.",
      },
      {
        "en": "Technology has changed our lives significantly.",
        "tr": "Teknoloji hayatımızı önemli ölçüde değiştirdi.",
      },
      {
        "en": "It is important to eat healthy food.",
        "tr": "Sağlıklı yiyecekler yemek önemlidir.",
      },
      {
        "en": "I used to play tennis when I was young.",
        "tr": "Gençken tenis oynardım.",
      },
      {
        "en": "Have you ever been to London?",
        "tr": "Hiç Londra'da bulundun mu?",
      },
      {
        "en": "I will finish the report by tomorrow.",
        "tr": "Raporu yarına kadar bitireceğim.",
      },
      {
        "en": "She asked me if I was ready.",
        "tr": "Bana hazır olup olmadığımı sordu.",
      },
      {
        "en": "The book was written by a famous author.",
        "tr": "Kitap ünlü bir yazar tarafından yazıldı.",
      },
      {
        "en": "Whatever happens, don't give up.",
        "tr": "Ne olursa olsun, pes etme.",
      },
      {
        "en": "I look forward to hearing from you.",
        "tr": "Sizden haber almayı dört gözle bekliyorum.",
      },
      {
        "en": "He succeeded in passing the exam.",
        "tr": "Sınavı geçmeyi başardı.",
      },
      {
        "en": "Pollution is a major global problem.",
        "tr": "Kirlilik büyük bir küresel sorundur.",
      },
      {
        "en": "We need to protect the environment.",
        "tr": "Çevreyi korumamız gerekiyor.",
      },
      {
        "en": "Education is the key to success.",
        "tr": "Eğitim başarının anahtarıdır.",
      },
      {
        "en": "I am thinking of changing my job.",
        "tr": "İşimi değiştirmeyi düşünüyorum.",
      },
    ],
    'B2': [
      {
        "en": "The economic situation is getting worse.",
        "tr": "Ekonomik durum kötüleşiyor.",
      },
      {
        "en": "It is widely believed that health is wealth.",
        "tr": "Yaygın bir inanıştır ki sağlık zenginliktir.",
      },
      {
        "en": "Despite the challenges, we succeeded.",
        "tr": "Zorluklara rağmen başardık.",
      },
      {
        "en": "I would rather stay home than go out.",
        "tr": "Dışarı çıkmaktansa evde kalmayı tercih ederim.",
      },
      {
        "en": "He is accused of stealing the money.",
        "tr": "Parayı çalmakla suçlanıyor.",
      },
      {
        "en": "The results provided by the study are conclusive.",
        "tr": "Çalışmanın sağladığı sonuçlar kesindir.",
      },
      {
        "en": "You must take all factors into consideration.",
        "tr": "Tüm faktörleri göz önünde bulundurmalısınız.",
      },
      {
        "en": "It is essential to maintain a balanced diet.",
        "tr": "Dengeli bir beslenme sürdürmek esastır.",
      },
      {
        "en": "The government implemented new policies.",
        "tr": "Hükümet yeni politikalar uyguladı.",
      },
      {
        "en": "Sustainable energy is vital for the future.",
        "tr": "Sürdürülebilir enerji gelecek için hayati önem taşır.",
      },
      {
        "en": "She has a tendency to exaggerate things.",
        "tr": "Olayları abartma eğilimi var.",
      },
      {
        "en": "This theory has not been proven yet.",
        "tr": "Bu teori henüz kanıtlanmadı.",
      },
      {
        "en": "The impact of climate change is undeniable.",
        "tr": "İklim değişikliğinin etkisi inkar edilemez.",
      },
      {
        "en": "We must adapt to the changing circumstances.",
        "tr": "Değişen koşullara uyum sağlamalıyız.",
      },
      {
        "en": "Negotiations between the two countries failed.",
        "tr": "İki ülke arasındaki müzakereler başarısız oldu.",
      },
      {
        "en": "He has made a significant contribution to science.",
        "tr": "Bilime önemli bir katkıda bulundu.",
      },
      {
        "en": "It is rumored that the company will be sold.",
        "tr": "Şirketin satılacağı söyleniyor.",
      },
      {
        "en": "I demand an explanation for this behavior.",
        "tr": "Bu davranış için bir açıklama talep ediyorum.",
      },
      {
        "en": "The complexity of the issue requires careful analysis.",
        "tr": "Konunun karmaşıklığı dikkatli bir analiz gerektirir.",
      },
      {
        "en": "We are committed to providing quality service.",
        "tr": "Kaliteli hizmet sunmaya kararlıyız.",
      },
    ],
  };
}
